language: go

notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: true
      go: 1.12.x
      before_install:
        - wget -O $ANDROID_HOME/android-ndk-r19b-linux-x86_64.zip https://dl.google.com/android/repository/android-ndk-r19b-linux-x86_64.zip
        - unzip -qq $ANDROID_HOME/android-ndk-r19b-linux-x86_64.zip -d $ANDROID_HOME/android-ndk-r19b-linux-x86_64
        - mv $ANDROID_HOME/android-ndk-r19b-linux-x86_64/android-ndk-r19b $ANDROID_HOME/ndk-bundle
        - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
        - go get -u golang.org/x/mobile/cmd/gomobile
        - echo $ANDROID_NDK_HOME
      script:
        - make build
        - make test
        - make buildandroid

    - os: osx
      osx_image: xcode10.1
      sudo: true
      go: 1.12.x
      before_install:
        - go get -u golang.org/x/mobile/cmd/gomobile
      script:
        - make build
        - make test
        - make buildosx

after_success:
  # send coverage reports to Codecov
  - bash <(curl -s https://codecov.io/bash) -f "!mock.go"
